

$env:JAVA_HOME = "C:\Program Files\Java\jdk-21.0.10"
$env:PATH = "$env:JAVA_HOME\bin;" + $env:PATH


$env:EMAIL_ADDRESS="it80@ytpr.in"
$env:EMAIL_APP_PASSWORD="SSYYTTure@1212"
$env:EMAIL_ADDRESS_1="it81@ytpr.in"
$env:EMAIL_APP_PASSWORD_1="SSYYTTure@1212"
$env:EMAIL_ADDRESS_2="it82@ytpr.in"
$env:EMAIL_APP_PASSWORD_2="SSYYTTure@1212"
$env:EMAIL_ADDRESS_3="it83@ytpr.in"
$env:EMAIL_APP_PASSWORD_3="SSYYTTure@1212"
$env:EMAIL_ADDRESS_4="it84@ytpr.in"
$env:EMAIL_APP_PASSWORD_4="SSYYTTure@1212"
$env:EMAIL_ADDRESS_5="it85@ytpr.in"
$env:EMAIL_APP_PASSWORD_5="SSYYTTure@1212"
$env:EMAIL_ADDRESS_6="it86@ytpr.in"
$env:EMAIL_APP_PASSWORD_6="SSYYTTure@1212"
$env:EMAIL_ADDRESS_7="it87@ytpr.in"
$env:EMAIL_APP_PASSWORD_7="SSYYTTure@1212"
$env:EMAIL_ADDRESS_8="it88@ytpr.in"
$env:EMAIL_APP_PASSWORD_8="SSYYTTure@1212"
$env:EMAIL_ADDRESS_9="it89@ytpr.in"
$env:EMAIL_APP_PASSWORD_9="SSYYTTure@1212"
$env:EMAIL_ADDRESS_10="it90@ytpr.in"
$env:EMAIL_APP_PASSWORD_10="SSYYTTure@1212"
$env:IMAP_SERVER="imap.hostinger.com"
$env:APPLICATIONS_FILE="applications.json"
$env:NUM_WORKERS="4"
$env:HEADLESS="true"
$env:STORAGE_MODE="local"
$env:BROWSER_TIMEOUT="60000"
$env:APP_TIMEOUT_SECONDS="250"
java -jar target/scraper-1.0.0.jar | Tee-Object -FilePath "scraper.log"
